fringeclass/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include

from django.views.static import serve
from django.views.defaults import bad_request
from django.views.defaults import server_error
from django.views.defaults import page_not_found
from django.views.defaults import permission_denied
from django.views.generic.base import RedirectView
from django.contrib.sitemaps.views import index
from django.contrib.sitemaps.views import sitemap

from django_xmlrpc.views import handle_xmlrpc

from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import AuthorSitemap

urlpatterns = [
	url(r'^$', 'fringeclass.views.index'),
    url(r'^$', RedirectView.as_view(url='/blog/', permanent=True)),
    url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^xmlrpc/$', handle_xmlrpc),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
]

sitemaps = {
    'tags': TagSitemap,
    'blog': EntrySitemap,
    'authors': AuthorSitemap,
    'categories': CategorySitemap
}

urlpatterns += [
    url(r'^sitemap.xml$',
        index,
        {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap,
        {'sitemaps': sitemaps}),
]

urlpatterns += [
    url(r'^400/$', bad_request),
    url(r'^403/$', permission_denied),
    url(r'^404/$', page_not_found),
    url(r'^500/$', server_error),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT})
    ]

zinnia/models/category.py
"""Category model for Zinnia"""
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from mptt.models import MPTTModel
from mptt.models import TreeForeignKey
from mptt.managers import TreeManager

from zinnia.managers import entries_published
from zinnia.managers import EntryRelatedPublishedManager


@python_2_unicode_compatible
class Category(MPTTModel):
    """
    Simple model for categorizing entries.
    """

    title = models.CharField(
        _('title'), max_length=255)

    slug = models.SlugField(
        _('slug'), unique=True, max_length=255,
        help_text=_("Used to build the category's URL."))

    description = models.TextField(
        _('description'), blank=True)

    parent = TreeForeignKey(
        'self',
        related_name='children',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('parent category'))

    objects = TreeManager()
    published = EntryRelatedPublishedManager()

    def entries_published(self):
        """
        Returns category's published entries.
        """
        return entries_published(self.entries)

    @property
    def tree_path(self):
        """
        Returns category's tree path
        by concatening the slug of his ancestors.
        """
        if self.parent_id:
            return '/'.join(
                [ancestor.slug for ancestor in self.get_ancestors()] +
                [self.slug])
        return self.slug

    @models.permalink
    def get_absolute_url(self):
        """
        Builds and returns the category's URL
        based on his tree path.
        """
        return ('zinnia:category_detail', (self.tree_path,))

    def __str__(self):
        return self.title

    class Meta:
        """
        Category's meta informations.
        """
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    class MPTTMeta:
        """
        Category MPTT's meta informations.
        """
        order_insertion_by = ['title']

zinnia/models/entry.py
"""Entry model for Zinnia"""
from zinnia.settings import ENTRY_BASE_MODEL
from zinnia.models_bases import load_model_class


class Entry(load_model_class(ENTRY_BASE_MODEL)):
    """
    The final Entry model based on inheritence.
    """

zinnia/views/archives.py
"""Views for Zinnia archives"""
import datetime

from django.utils import timezone
from django.views.generic.dates import BaseArchiveIndexView
from django.views.generic.dates import BaseYearArchiveView
from django.views.generic.dates import BaseMonthArchiveView
from django.views.generic.dates import BaseWeekArchiveView
from django.views.generic.dates import BaseDayArchiveView
from django.views.generic.dates import BaseTodayArchiveView

from zinnia.models.entry import Entry
from zinnia.views.mixins.archives import ArchiveMixin
from zinnia.views.mixins.archives import PreviousNextPublishedMixin
from zinnia.views.mixins.callable_queryset import CallableQuerysetMixin
from zinnia.views.mixins.prefetch_related import PrefetchCategoriesAuthorsMixin
from zinnia.views.mixins.templates import \
    EntryQuerysetArchiveTemplateResponseMixin
from zinnia.views.mixins.templates import \
    EntryQuerysetArchiveTodayTemplateResponseMixin


class EntryArchiveMixin(ArchiveMixin,
                        PreviousNextPublishedMixin,
                        PrefetchCategoriesAuthorsMixin,
                        CallableQuerysetMixin,
                        EntryQuerysetArchiveTemplateResponseMixin):
    """
    Mixin combinating:

    - ArchiveMixin configuration centralizing conf for archive views.
    - PrefetchCategoriesAuthorsMixin to prefetch related objects.
    - PreviousNextPublishedMixin for returning published archives.
    - CallableQueryMixin to force the update of the queryset.
    - EntryQuerysetArchiveTemplateResponseMixin to provide a
      custom templates for archives.
    """
    queryset = Entry.published.all


class EntryIndex(EntryArchiveMixin,
                 EntryQuerysetArchiveTodayTemplateResponseMixin,
                 BaseArchiveIndexView):
    """
    View returning the archive index.
    """
    context_object_name = 'entry_list'


class EntryYear(EntryArchiveMixin, BaseYearArchiveView):
    """
    View returning the archives for a year.
    """
    make_object_list = True
    template_name_suffix = '_archive_year'


class EntryMonth(EntryArchiveMixin, BaseMonthArchiveView):
    """
    View returning the archives for a month.
    """
    template_name_suffix = '_archive_month'


class EntryWeek(EntryArchiveMixin, BaseWeekArchiveView):
    """
    View returning the archive for a week.
    """
    template_name_suffix = '_archive_week'

    def get_dated_items(self):
        """
        Override get_dated_items to add a useful 'week_end_day'
        variable in the extra context of the view.
        """
        self.date_list, self.object_list, extra_context = super(
            EntryWeek, self).get_dated_items()
        self.date_list = self.get_date_list(self.object_list, 'day')
        extra_context['week_end_day'] = extra_context[
            'week'] + datetime.timedelta(days=6)
        return self.date_list, self.object_list, extra_context


class EntryDay(EntryArchiveMixin, BaseDayArchiveView):
    """
    View returning the archive for a day.
    """
    template_name_suffix = '_archive_day'


class EntryToday(EntryArchiveMixin, BaseTodayArchiveView):
    """
    View returning the archive for the current day.
    """
    template_name_suffix = '_archive_today'

    def get_dated_items(self):
        """
        Return (date_list, items, extra_context) for this request.
        And defines self.year/month/day for
        EntryQuerysetArchiveTemplateResponseMixin.
        """
        now = timezone.now()
        if timezone.is_aware(now):
            now = timezone.localtime(now)
        today = now.date()
        self.year, self.month, self.day = today.isoformat().split('-')
        return self._get_dated_items(today)

zinnia/views/authors.py
"""Views for Zinnia authors"""
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.list import BaseListView

from zinnia.settings import PAGINATION
from zinnia.models.author import Author
from zinnia.views.mixins.templates import EntryQuerysetTemplateResponseMixin
from zinnia.views.mixins.prefetch_related import PrefetchCategoriesAuthorsMixin


class AuthorList(ListView):
    """
    View returning a list of all published authors.
    """

    def get_queryset(self):
        """
        Return a queryset of published authors,
        with a count of their entries published.
        """
        return Author.published.all().annotate(
            count_entries_published=Count('entries'))


class BaseAuthorDetail(object):
    """
    Mixin providing the behavior of the author detail view,
    by returning in the context the current author and a
    queryset containing the entries written by author.
    """

    def get_queryset(self):
        """
        Retrieve the author by his username and
        build a queryset of his published entries.
        """
        self.author = get_object_or_404(
            Author, **{Author.USERNAME_FIELD: self.kwargs['username']})
        return self.author.entries_published()

    def get_context_data(self, **kwargs):
        """
        Add the current author in context.
        """
        context = super(BaseAuthorDetail, self).get_context_data(**kwargs)
        context['author'] = self.author
        return context


class AuthorDetail(EntryQuerysetTemplateResponseMixin,
                   PrefetchCategoriesAuthorsMixin,
                   BaseAuthorDetail,
                   BaseListView):
    """
    Detailed view for an Author combinating these mixins:

    - EntryQuerysetTemplateResponseMixin to provide custom templates
      for the author display page.
    - PrefetchCategoriesAuthorsMixin to prefetch related Categories
      and Authors to belonging the entry list.
    - BaseAuthorDetail to provide the behavior of the view.
    - BaseListView to implement the ListView.
    """
    model_type = 'author'
    paginate_by = PAGINATION

    def get_model_name(self):
        """
        The model name is the author's username.
        """
        return self.author.get_username()

zinnia/views/capabilities.py
"""Views for Zinnia capabilities"""
from django.contrib.sites.models import Site
from django.views.generic.base import TemplateView

from zinnia.settings import PROTOCOL
from zinnia.settings import COPYRIGHT
from zinnia.settings import FEEDS_FORMAT


class CapabilityView(TemplateView):
    """
    Base view for the weblog capabilities.
    """

    def get_context_data(self, **kwargs):
        """
        Populate the context of the template
        with technical informations for building urls.
        """
        context = super(CapabilityView, self).get_context_data(**kwargs)
        context.update({'protocol': PROTOCOL,
                        'copyright': COPYRIGHT,
                        'feeds_format': FEEDS_FORMAT,
                        'site': Site.objects.get_current()})
        return context


class HumansTxt(CapabilityView):
    """
    http://humanstxt.org/
    """
    content_type = 'text/plain'
    template_name = 'zinnia/humans.txt'


class RsdXml(CapabilityView):
    """
    http://en.wikipedia.org/wiki/Really_Simple_Discovery
    """
    content_type = 'application/rsd+xml'
    template_name = 'zinnia/rsd.xml'


class WLWManifestXml(CapabilityView):
    """
    http://msdn.microsoft.com/en-us/library/bb463260.aspx
    """
    content_type = 'application/wlwmanifest+xml'
    template_name = 'zinnia/wlwmanifest.xml'


class OpenSearchXml(CapabilityView):
    """
    http://www.opensearch.org/
    """
    content_type = 'application/opensearchdescription+xml'
    template_name = 'zinnia/opensearch.xml'

zinnia/views/categories.py
"""Views for Zinnia categories"""
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.list import BaseListView

from zinnia.models.category import Category
from zinnia.settings import PAGINATION
from zinnia.views.mixins.templates import EntryQuerysetTemplateResponseMixin
from zinnia.views.mixins.prefetch_related import PrefetchCategoriesAuthorsMixin


def get_category_or_404(path):
    """
    Retrieve a Category instance by a path.
    """
    path_bits = [p for p in path.split('/') if p]
    return get_object_or_404(Category, slug=path_bits[-1])


class CategoryList(ListView):
    """
    View returning a list of published categories.
    """

    def get_queryset(self):
        """
        Return a queryset of published categories,
        with a count of their entries published.
        """
        return Category.published.all().annotate(
            count_entries_published=Count('entries'))


class BaseCategoryDetail(object):
    """
    Mixin providing the behavior of the category detail view,
    by returning in the context the current category and a
    queryset containing the entries published under it.
    """

    def get_queryset(self):
        """
        Retrieve the category by his path and
        build a queryset of her published entries.
        """
        self.category = get_category_or_404(self.kwargs['path'])
        return self.category.entries_published()

    def get_context_data(self, **kwargs):
        """
        Add the current category in context.
        """
        context = super(BaseCategoryDetail, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context


class CategoryDetail(EntryQuerysetTemplateResponseMixin,
                     PrefetchCategoriesAuthorsMixin,
                     BaseCategoryDetail,
                     BaseListView):
    """
    Detailed view for a Category combinating these mixins:

    - EntryQuerysetTemplateResponseMixin to provide custom templates
      for the category display page.
    - PrefetchCategoriesAuthorsMixin to prefetch related Categories
      and Authors to belonging the entry list.
    - BaseCategoryDetail to provide the behavior of the view.
    - BaseListView to implement the ListView.
    """
    model_type = 'category'
    paginate_by = PAGINATION

    def get_model_name(self):
        """
        The model name is the category's slug.
        """
        return self.category.slug

zinnia/views/channels.py
"""Views for Zinnia channels"""
from django.views.generic.list import ListView

from zinnia.models.entry import Entry
from zinnia.settings import PAGINATION
from zinnia.views.mixins.prefetch_related import PrefetchCategoriesAuthorsMixin


class BaseEntryChannel(object):
    """
    Mixin for displaying a custom selection of entries
    based on a search query, useful to build SEO/SMO pages
    aggregating entries on a thematic or for building a
    custom homepage.
    """
    query = ''

    def get_queryset(self):
        """
        Override the get_queryset method to build
        the queryset with entry matching query.
        """
        return Entry.published.search(self.query)

    def get_context_data(self, **kwargs):
        """
        Add query in context.
        """
        context = super(BaseEntryChannel, self).get_context_data(**kwargs)
        context.update({'query': self.query})
        return context


class EntryChannel(PrefetchCategoriesAuthorsMixin,
                   BaseEntryChannel,
                   ListView):
    """
    Channel view for entries combinating these mixins:

    - PrefetchCategoriesAuthorsMixin to prefetch related Categories
      and Authors to belonging the entry list.
    - BaseEntryChannel to provide the behavior of the view.
    - ListView to implement the ListView and template name resolution.
    """
    paginate_by = PAGINATION

zinnia/views/comments.py
"""Views for Zinnia comments"""
from django.template.defaultfilters import slugify
from django.http import HttpResponsePermanentRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic.base import View
from django.views.generic.base import TemplateResponseMixin

import django_comments as comments


class CommentSuccess(TemplateResponseMixin, View):
    """
    View for handing the publication of a Comment on an Entry.
    Do a redirection if the comment is visible,
    else render a confirmation template.
    """
    template_name = 'comments/zinnia/entry/posted.html'

    def get_context_data(self, **kwargs):
        return {'comment': self.comment}

    def get(self, request, *args, **kwargs):
        self.comment = None

        if 'c' in request.GET:
            try:
                self.comment = comments.get_model().objects.get(
                    pk=request.GET['c'])
            except (ObjectDoesNotExist, ValueError):
                pass
        if self.comment and self.comment.is_public:
            return HttpResponsePermanentRedirect(
                self.comment.get_absolute_url(
                    '#comment-%(id)s-by-') + slugify(self.comment.user_name))

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

zinnia/views/random.py
"""Views for Zinnia random entry"""
from django.views.generic.base import RedirectView

from zinnia.models.entry import Entry


class EntryRandom(RedirectView):
    """
    View for handling a random entry
    simply do a redirection after the random selection.
    """
    permanent = False

    def get_redirect_url(self, **kwargs):
        """
        Get entry corresponding to 'pk' and
        return the get_absolute_url of the entry.
        """
        entry = Entry.published.all().order_by('?')[0]
        return entry.get_absolute_url()

templates/zinnia/author_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Author list" %}{% endblock meta-description %}

{% block title %}{% trans "Authors" %}{% endblock title %}

{% block body-class %}author-list{% endblock body-class %}

{% block content %}
<h1>{% trans "Author list" %}</h1>

<ul>
  {% for object in object_list %}
  <li class="vcard">
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}"
       class="fn url{% if not author.get_full_name %} nickname{% endif %}">{{ object }}</a>
    {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
  </li>
  {% empty %}
  <li>
    {% trans "No authors yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

templates/zinnia/base.html
{% extends "index.html" %}
{# optional: load additional tags #} 
{% load i18n %}
{% load zinnia %}
{# optional: replace content of your blocks by zinnia equivalents, e.g. #}
{% block breadcrumbs %}{% zinnia_breadcrumbs %}{% endblock breadcrumbs %} 

templates/zinnia/category_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}
{% load mptt_tags %}

{% block meta-description %}{% trans "Category list" %}{% endblock meta-description %}

{% block title %}{% trans "Categories" %}{% endblock title %}

{% block body-class %}category-list{% endblock body-class %}

{% block content %}
<h1>{% trans "Category list" %}</h1>

<ul>
  {% for object in object_list %}
  <li>
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with category=object %}Show all entries in {{ category }}{% endblocktrans %}">{{ object }}</a>
    {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    {% if object.description %}<p>{{ object.description|striptags|safe }}</p>{% endif %}
  </li>
  {% empty %}
  <li>
    {% trans "No categories yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

templates/zinnia/entry_archive.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% trans "Last entries" %}{% endblock meta-description %}

{% block title %}{% trans "Last entries" %}{% endblock title %}

{% block body-class %}{{ block.super }} archive index {% now "\y\e\a\r-Y \m\o\n\t\h-m \w\e\ek-W \d\a\y-d" %}{% endblock body-class %}

{% block slider %}
{% get_featured_entries template="zinnia/tags/entries_slider.html" %}
{% endblock slider %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Yearly archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_year' date|date:"Y" %}" rel="archives">{{ date|date:"Y" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock content-related %}

templates/zinnia/entry_archive_today.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Today archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock meta-description %}

{% block title %}{% trans "Today archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date today year-{{ day|date:"Y" }} month-{{ day|date:"m" }} week-{{ day|date:"W" }} day-{{ day|date:"d" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Today archives" %}</h1>
{% endblock content-title %}

{% block content-related %}
{% if previous_day %}
<h3>{% trans "Previous day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' previous_day|date:"Y" previous_day|date:"m" previous_day|date:"d" %}" rel="archives">{{ previous_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}

<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' day|date:"Y" %}" rel="archives">{{ day|date:"Y" }}</a>
  </li>
  {% if previous_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' day|date:"Y" day|date:"m" %}" rel="archives">{{ day|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
<ul>
{% endblock content-related %}

templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% spaceless %}
{% if category %}
{% if category.description %}
{{ category.description|striptags|safe }}
{% else %}
{% blocktrans with object=category %}The last entries categorized under {{ object }}{% endblocktrans %}
{% endif %}
{% endif %}

{% if tag %}
{% blocktrans with object=tag %}The last entries tagged with {{ object }}{% endblocktrans %}
{% endif %}

{% if author %}
{% blocktrans with object=author %}The last entries by {{ object }}{% endblocktrans %}
{% endif %}

{% endspaceless %}{% endblock meta-description %}

{% block meta-description-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% blocktrans with object=page_obj.number %}page {{ object }}{% endblocktrans %}{% endifnotequal %}{% endif %}{% endblock meta-description-page %}

{% block title %}{% spaceless %}
{% if category %}
{% blocktrans with object=category %}Category {{ object }}{% endblocktrans %}
{% endif %}

{% if tag %}
{% blocktrans with object=tag %}Tag {{ object }}{% endblocktrans %}
{% endif %}

{% if author %}
{% blocktrans with object=author %}Author {{ object }}{% endblocktrans %}
{% endif %}

{% endspaceless %}{% endblock title %}

{% block title-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} - {% blocktrans with object=page_obj.number %}Page {{ object }}{% endblocktrans %}{% endifnotequal %}{% endif %}{% endblock title-page %}

{% block link %}
  {{ block.super }}
  {% if category %}
    <link rel="alternate" type="application/rss+xml" title="{% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}" href="{% url 'zinnia:category_feed' category.tree_path %}" />
  {% endif %}
  {% if tag %}
    <link rel="alternate" type="application/rss+xml" title="{% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}" href="{% url 'zinnia:tag_feed' tag.name %}" />
  {% endif %}
  {% if author %}
    <link rel="alternate" type="application/rss+xml" title="{% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}" href="{% url 'zinnia:author_feed' author.get_username %}" />
  {% endif %}
{% endblock link %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %} category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %} author author-{{ author|slugify }}{% endif %}{% endblock body-class %}

{% block content %}

{% block content-title %}
{% if category %}
<h1>{% blocktrans %}Category archives: {{ category }}{% endblocktrans %}</h1>
{% if category.description %}
<p>{{ category.description|striptags|safe }}</p>
{% endif %}
<p class="feed">
  <a href="{% url 'zinnia:category_feed' category.tree_path %}" title="{% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}">
    {% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}
  </a>
</p>
{% endif %}

{% if tag %}
<h1>{% blocktrans %}Tag archives: {{ tag }}{% endblocktrans %}</h1>
<p class="feed">
  <a href="{% url 'zinnia:tag_feed' tag.name %}" title="{% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}">
    {% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}
  </a>
</p>
{% endif %}

{% if author %}
<h1>{% blocktrans %}Author archives: {{ author }}{% endblocktrans %}</h1>
<p class="feed">
  <a href="{% url 'zinnia:author_feed' author.get_username %}" title="{% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}">
    {% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}
  </a>
</p>
{% endif %}
{% endblock content-title %}

{% block content-loop %}
{% for object in object_list %}
  {% zinnia_loop_template object.content_template as template %}
  {% include template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
  <p class="info">
    <a href="{% url 'admin:zinnia_entry_add' %}">{% trans "No entries yet." %}</a>
  </p>
{% endfor %}
{% endblock content-loop %}

{% block content-pagination %}
{% if is_paginated %}
  {% zinnia_pagination page_obj %}
{% endif %}
{% endblock content-pagination %}

{% block content-related %}
{% endblock content-related %}

{% endblock content %}

{% block admin-tools %}
  {% if category and perms.zinnia.change_category %}
  <li>
    <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}">
      {% trans "Edit the category" %}
    </a>
  </li>
  {% endif %}
  {% if tag and perms.tagging.change_tag %}
  <li>
    <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}">
      {% trans "Edit the tag" %}
    </a>
  </li>
  {% endif %}
  {% if author and perms.auth.change_user %}
  <li>
    <a href="{% url 'change'|user_admin_urlname author.pk %}" title="{% trans "Edit the author" %}">
      {% trans "Edit the author" %}
    </a>
  </li>
  {% endif %}
{% endblock admin-tools %}